### ISSUE TITLE
[BUG]服务启动不了吗，或者怎么设置开机自启呢？

### ISSUE THREAD

**Issue by Rebellce** [xlc520/easytier-manager#3]
### App 版本

3.0.0

### 内核版本

2.0.3

### 请描述您的需求或者改进建议

问题如图，
安装和启动服务都显示成功，但是无法连接。
或者有其他方法设置开机自启呢？
谢谢。

### 附加信息

![image](https://github.com/user-attachments/assets/488cf5d9-a714-49ef-a2e5-097d57254bf6)
![image](https://github.com/user-attachments/assets/862b51c2-1bfe-4e6d-9ba5-e5f9250a086c)
![image](https://github.com/user-attachments/assets/b926ab82-587f-4a2e-a6eb-b3b5841ed729)

**Comment by xlc520** [comment]
等研究一下看看

**Comment by xlc520** [comment]
试一下最新版更改了一些API，看看能不能解决，[EasyTier 管理器 Pro v3.0.1](https://github.com/xlc520/easytier-manager/releases/tag/v3.0.1)

**Comment by Rebellce** [comment]
![image](https://github.com/user-attachments/assets/c13b03ea-f216-49f9-b93c-e19df8331dad)
辛苦了，显示成功了但是打开服务还是暂停状态，不知道是否成功。该怎么验证？
![image](https://github.com/user-attachments/assets/b597afc5-f035-4ea8-81a1-5e7a4b13f4f4)

**Comment by Rebellce** [comment]
也可能是我的个人原因，电脑上乱七八糟的东西装的太多了hh

**Comment by xlc520** [comment]
这个可以重新进服务，刷新看看，启动成功的话，可以试试ping组网的另一台设备看通不通，建议先停止服务，在工作台运行看看组网有没有数据更新，有就正常，并试试ping一起组网的设备

**Comment by Rebellce** [comment]
刷新了以后又变成未知了，服务在我的电脑上还是跑不起来，不知道其他人有没有同样的问题。
![image](https://github.com/user-attachments/assets/b81e31c9-3ebd-4ae5-af51-d166cd447e7d)
![image](https://github.com/user-attachments/assets/e2e5a7f3-6987-4b04-b927-f110a2666674)
 再附一张window的版本

**Comment by xlc520** [comment]
先在工作台运行看看有什么问题，只要有你组网的节点刷新出来，配置就没问题，在安装服务测试。
其次，24H2确实有点问题，据反馈应该是权限收紧，导致没有权限执行，可以尝试把安装目录的那些exe赋予完全控制权限。实在用不了还是用官方的GUI
![image](https://github.com/user-attachments/assets/fbfe06b7-6518-413c-92b4-0ee3b37b155d)

**Comment by Rebellce** [comment]
嗯嗯好的，直接在工作台打开是可以正常使用的，现在唯一的问题就是不能开机自启，出门可以用todesk先连一下再打开也无伤大雅。官方的gui我修改配置后退出，配置每次都不保存，每次得重新添加节点，重新安装了也没用干脆先试试其他的gui了。项目很好，感谢帮助。

**Comment by 1023386568** [comment]
![image](https://github.com/user-attachments/assets/6b5a7a1e-b08d-4925-9d80-ab5d6bb0987d)
我工作台正常使用，但服务启动后就自动暂停了

**Comment by xlc520** [comment]
> ![image](https://private-user-images.githubusercontent.com/79915693/396333515-6b5a7a1e-b08d-4925-9d80-ab5d6bb0987d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDYxMjksIm5iZiI6MTczNDQwNTgyOSwicGF0aCI6Ii83OTkxNTY5My8zOTYzMzM1MTUtNmI1YTdhMWUtYjA4ZC00OTI1LTlkODAtYWI1ZDZiYjA5ODdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWY4YTkwMDBkYTRmYjIxNTUxZGZiZjAzMWFhOGI1ODE5ZjBiNTJmZmJlMGJiYTRjZGVkZmI0ZjVmYTNjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.anjZGGNsKm5Ggtj4MDweTijd8ImIn_OqViEYuhq6-Oo) 我工作台正常使用，但服务启动后就自动暂停了

第一次启动服务可能有点慢，管理器的配置界面关闭重新启动是否正常显示，系统服务可以关闭重新打开看看，如果还是有问题，打开日志目录把日志发来，包括easytier-manager-pro.log和另一个带有当前日期的

**Comment by 1023386568** [comment]
[logs.zip](https://github.com/user-attachments/files/18159694/logs.zip)

**Comment by 1023386568** [comment]
另一个文件格式传不了，我打包传上来

**Comment by ynwessnso** [comment]
安装目录不能有空格，不要安装在Program Files这个目录，换个每空格的目录就可以正常启动了。easytier启动命令不能有空格，尝试多次安装才发现这个问题

**Comment by Rebellce** [comment]
> 安装目录不能有空格，不要安装在Program Files这个目录，换个每空格的目录就可以正常启动了。easytier启动命令不能有空格，尝试多次安装才发现这个问题

是的，目前核心换 2.1.1，APP 3.0.2，采用无空格无中文路径可以成功安装服务了

**Comment by kettly1260** [comment]
> > 安装目录不能有空格，不要安装在Program Files这个目录，换个每空格的目录就可以正常启动了。easytier启动命令不能有空格，尝试多次安装才发现这个问题
> 
> 是的，目前核心换 2.1.1，APP 3.0.2，采用无空格无中文路径可以成功安装服务了

意思是不能安装到默认文件夹吗

**Comment by jdjxk** [comment]
> > 安装目录不能有空格，不要安装在Program Files这个目录，换个每空格的目录就可以正常启动了。easytier启动命令不能有空格，尝试多次安装才发现这个问题
> 
> 是的，目前核心换 2.1.1，APP 3.0.2，采用无空格无中文路径可以成功安装服务了

感谢，问题解决

**Comment by HiramYang** [comment]
windows：核心如果是v2.3.0，easytier管理器pro版本是v3.1.0。可以安装服务，但是不能正常启动。点击开启服务，状态为未知。
核心为v2.2.4，easytier管理器pro版本是v3.1.0。服务才能正常运行。
